#
# sqlcmd = paste("select ",
#                "fd.FID,",
#                "fd.FTYPE,",
#                "fd.DATE,",
#                "fd.TIMESTAMP,",
#                "fd.MACHINE,",
#                "fd.LANE,",
#                "fd.STAGE,",
#                "fd.OUTPUT,",
#                "fd.MJSID,",
#                "fd.LOTNAME,",
#                "fd.LOTNUMBER,",
#                "fd.SERIAL,",
#                "fd.PRODUCTID,",
#                "fd.PRODUCT,",
#                "c.BNDRcgStop,",
#                "c.BNDStop,",
#                "c.Board,",
#                "c.BRcgStop,",
#                "c.Bwait,",
#                "c.CDErr,",
#                "c.CMErr,",
#                "c.CnvStop,",
#                "c.CPErr,",
#                "c.CRErr,",
#                "c.CTErr,",
#                "c.Cwait,",
#                "c.FBStop,",
#                "c.Fwait,",
#                "c.JointPassWait,",
#                "c.JudgeStop,",
#                "c.LotBoard,",
#                "c.LotModule,",
#                "c.McFwait,",
#                "c.McRwait,",
#                "c.MHRcgStop,",
#                "c.Module,",
#                "c.OtherLStop,",
#                "c.OthrStop,",
#                "c.Pwait,",
#                "c.Rwait,",,
#                "c.SCEStop,",
#                "c.SCStop,",
#                "c.Swait,",
#                "c.TDispense,",
#                "c.TDMiss,",
#                "c.THMiss,",
#                "c.TMMiss,",
#                "c.TPickup,",
#                "c.TPMiss,",
#                "c.TPriming,",
#                "c.Trbl,",
#                "c.TRMiss,",
#                "c.TRSErr,",
#                "c.TRSMiss ",
#                "from FID_DATA fd ",
#                "inner join 'Count' c on fd.FID = c.FID limit 1000",
#                sep="")
#
install_and_load("sqldf")
#
sqlcmd = paste("select ",
               "fd.MACHINE,",
               "fd.LANE,",
               "fd.STAGE,",
               "fd.PRODUCT,",
               "fd.TIMESTAMP,",
               "fd.FID,",
               "fd.OUTPUT,",
               "fd.SERIAL,",
               "fd.PRODUCTID,",
               "c.* ",
               "from FID_DATA fd ",
               "inner join 'Count' c on fd.FID = c.FID ",
               "group by ",
               "fd.MACHINE,",
               "fd.LANE,",
               "fd.STAGE,",
               "fd.PRODUCT,",
               "fd.TIMESTAMP ",
               "order by ",
               "fd.MACHINE asc,",
               "fd.LANE asc,",
               "fd.STAGE asc,",
               "fd.PRODUCT asc,",
               "fd.TIMESTAMP asc",
               sep="")
#
sqlcmd2 = paste("select ",
               "fd.MACHINE,",
               "fd.LANE,",
               "fd.STAGE,",
               "fd.PRODUCT,",
               "fd.TIMESTAMP,",
               "fd.FID,",
               "fnm.FNAME,",
               "fd.OUTPUT,",
               "fd.SERIAL,",
               "fd.PRODUCTID,",
               "c.TPickup ",
               "from FID_DATA fd ",
               "inner join 'Count' c on fd.FID = c.FID ",
               "inner join 'FILENAME_TO_IDS' fnm on fd.FID = fnm.FID ",
               "group by ",
               "fd.MACHINE,",
               "fd.LANE,",
               "fd.STAGE,",
               "fd.PRODUCT,",
               "fd.TIMESTAMP ",
               "order by ",
               "fd.MACHINE asc,",
               "fd.LANE asc,",
               "fd.STAGE asc,",
               "fd.PRODUCT asc,",
               "fd.TIMESTAMP asc",
               sep="")
